docker-compose-yaml: docker-compose.yml

project: demo-druxtjs-org


environments:
  9.x:
    routes:
      - node:
        - demo.druxtjs.org
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: drush cron
        service: cli
