version: '2'
services:
  node:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      lagoon.type: node
    volumes:
      - .:/app:delegated
    environment:
      - LAGOON_LOCALDEV_HTTP_PORT=3000
      - LAGOON_ROUTE=http://demo-druxtjs-org.docker.amazee.io
      - NUXT_HOST=0.0.0.0

networks:
  amazeeio-network:
    external: true
