version: '2'

services:
  node:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
        GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
        OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
    labels:
      lagoon.type: node
    volumes:
      - .:/app:delegated
    environment:
      LAGOON_LOCALDEV_HTTP_PORT: 3000
      LAGOON_ROUTE: http://demo-druxtjs-org.docker.amazee.io

networks:
  amazeeio-network:
    external: true
